version: '3.8'
services:
  db:
    image: postgres:12
    volumes:
      - type: bind
        source: ./data/db
        target: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8080:8080"
    depends_on:
      - db